### ISSUE TITLE
Should i create my own plan.php file in the config folder?

### ISSUE THREAD

**Issue by FWSimon** [theseanstewart/Plan-Config#1]
Hi,

Really nice package, this is something laravel is missing.

But im not sure if i should grab the file from here https://github.com/theseanstewart/Plan-Config/blob/master/src/plans.php and then put it into my config folder?

**Comment by theseanstewart** [comment]
Thanks! After you install, you just need to create config/plans.php or run the following command which will add the file for you:

`php artisan vendor:publish`

**Comment by FWSimon** [comment]
@theseanstewart I did run the PHP artisan vendor:publish, but didn't saw a `plans.php` file, will try again :) Thanks!
